### ISSUE TITLE
Share my profile through a direct link so people can start talking to me

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#11]
So people can start talking to me.

https://www.sketch.com/s/aa87e1e9-2fa2-46fb-b2c7-5414cdf07cb3/a/YZYZVGL

**Comment by david-gauquelin** [comment]
Maybe at first we can do a simpler version with a "public link" (no unique link) we can use the same link and scan the same QR code

**Comment by vojtechsimetka** [comment]
I understood it that way. Basically I am sharing my account invite link which is pseudo private (it is 40+hex numbers which is hard to guess but always the same)

**Comment by agazso** [comment]
> I understood it that way. Basically I am sharing my account invite link which is pseudo private (it is 40+hex numbers which is hard to guess but always the same)

Can you please describe the flow in a bit more depth so that I can understand?
@filoozom feel free to also add your ideas, for example I would be interested if we could use a version of short codes?

**Comment by filoozom** [comment]
It might be possible to use short codes, but I'm not sure how secure my implementation actually is. For now I'd take the simplest route and have either a long link that contains all the useful info (maybe encoded in base64 or something to make it a bit shorter than a hex address) or some sort of on-chain registry to have shorter links. That would depend on the chain we'd use and the associated cost.

**Comment by vojtechsimetka** [comment]
> Can you please describe the flow in a bit more depth so that I can understand?

It was a response to @david-gauquelin suggestion to start with a non-unique link. So essentially the link being my ETH address.
