### ISSUE TITLE
Transaction id is too long

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#157]
The transaction id is too long, it breaks in several lines. It would be better to display just the six (or four) beginning and ending characters of the id with dots between. For example `0x800439...be3e28`.

Also the `#` is not needed because the identifiers are not sequential, but random and in the Ethereum ecosystem people are used to the `0x...` notation.

![Screenshot from 2023-07-05 21-33-58](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/75cea1bd-c96f-496b-8c10-eb8dfa3729dd)

**Comment by sugarpusher** [comment]
Yup we need to check in with David to see what the intention is for the transaction #. His design shows #001 so we're not sure what he wants. I left a comment in the code so we don't forget 😉

**Comment by david-gauquelin** [comment]
So the idea here was to have an unique identifier for a transaction. I didn't plan to use the actual transaction number, but rather a simple sequential number. Keep in mind that in the case of a request transaction we will not have an actual transaction number upfront, but we will still need this unique identifier (to help people distinguish between transactions if they have multiple active ones). In that case the "transaction" is the Payggy transaction, not necessarily and actual payment. Think also about a split payment scenario (for later) one Payggy transaction might have multiple payments associated to it (each with an actual transaction number). Does that make sense?

**Comment by david-gauquelin** [comment]
We had a conversation with @vojtechsimetka and @sugarpusher yesterday about this. @vojtechsimetka mentioned that we already have an "Instance ID" for Waku Objects instance, so we agreed to use the first 4 characters of that "Instance ID"

**Comment by david-gauquelin** [comment]
I updated both the Payggy and SafeMeet sketch files to reflect this change.
Note that I also remove that field from from the summary screen since this is not editable
