### ISSUE TITLE
Waku objects logo and favicon

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/waku-objects-playground#166]

**Comment by david-gauquelin** [comment]
Please specify :)

**Comment by vojtechsimetka** [comment]
I mean a general one for Waku Objects or for the chat app. This is of course not hight priority but I figured it makes sense to have an issue for this.

We do need favicon for our chat app (we did not do one for Kurate but it would be good to have one).

As for a logo, actually not sure if it is needed. But I guess we had something like that so I figured we might want to have it for WO as well.

![image](https://github.com/logos-innovation-lab/waku-objects-playground/assets/7974813/74c7d462-964b-4daa-98af-d6fd9b1dc460)

**Comment by david-gauquelin** [comment]
I see, and I'm not sure how do we want to approach this topic. Honestly, I like the less conventional, no-branding, no-logo, no-nonsense approach we had with Kurate. That image served us really well to communicate on the website and also made for a great tee shirt. Is it a logo? I'm not sure it definitely can be used as one (not at small sizes though, but maybe that's ok?). I would rather tackle this topic from a "what do we need this for" angle. Adding @michelleplur

**Comment by david-gauquelin** [comment]
Also I think we should differentiate between our demo chat application and Waku Objects. I'm not sure if any of these need a logo to be honest. Waku already has a logo see here https://waku.org/
