### ISSUE TITLE
Add an Apple Touch Icon so that the app can be added to ios home screen

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/waku-objects-playground#188]
Follow the steps below to add an Apple Touch Icon to your Svelte application. This icon will be displayed when your website is added to the home screen on iOS devices.

## 1. Create Your Icon

Firstly, you need to create a square icon for your website. The standard size for an Apple Touch Icon is 180x180 pixels. Ensure that it looks good against a variety of backgrounds, since you can't control what wallpaper the user will have on their device.

## 2. Add the Icon to the `public` Directory

Add your newly created icon to the `public` directory in your Svelte project. This is where all the static files, i.e., files that are not processed by Svelte, are located.

## 3. Update Your `index.html` File

You now need to reference your icon in the `index.html` file. You can do this by adding a `link` tag within the `head` tag of your HTML:

```html
<head>
  <!-- Other tags... -->
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
</head>
```

Replace "/apple-touch-icon.png" with the path to your icon if you've named it something different or if it's located somewhere other than the public directory.

## 4. Make Your Website Responsive

To ensure that your website looks good on all iOS devices, make it mobile responsive. You can use Svelte's built-in tools or other libraries like Svelte Material UI, Tailwind CSS, or Bootstrap with Svelte, depending on your preference.

## 5. Add the Viewport Meta Tag

Lastly, to ensure that your site scales correctly on mobile devices, include the viewport meta tag in your index.html file:

```html
Copy code
<head>
  <!-- Other tags... -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

## Optional: Add Meta Tags for SEO

While not strictly necessary for the icon, adding meta tags for SEO purposes can help search engines understand your site and improve its search rankings.

**Comment by michelleplur** [comment]
doing this now|

**Comment by michelleplur** [comment]
Clearly you used ChatGPT for this. Therefore, the information provided is wrong. Here is the correct documentation: https://dev.to/100lvlmaster/create-a-pwa-with-sveltekit-svelte-a36
