### ISSUE TITLE
Add scan QR code button to start chatting

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/waku-objects-playground#190]

**Comment by sugarpusher** [comment]
Can you elaborate on this?
We have this page already, is there another one?
https://www.sketch.com/s/98c659f4-66e3-4800-8c2b-ebc5125c5090
Thanks!

**Comment by vojtechsimetka** [comment]
So in this screen there should be scan QR code button which opens camera and can scan the invite QR code from counter party. We need this because if you add kurate as ios browser app, you have no way to start chatting.

![image](https://github.com/logos-innovation-lab/waku-objects-playground/assets/7974813/0abdb720-4c18-4c42-b505-0619f010c247)

**Comment by sugarpusher** [comment]
oh yeah makes total sense 😊

**Comment by vojtechsimetka** [comment]
Resolved in #192
