### ISSUE TITLE
Scrollable views are often 100% tall, scrolling looks weird

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#241]
The easiest to find out is to use the mobile view and choose a phone which has smaller screen (e.g. iPhone SE).

The identity screen has definitely this issue and I suspect others as well (e.g. I think the account screen if there are more currencies). I think it would be good to fix this problem in a systematic way, rather than fixing individual screen.

**Comment by sugarpusher** [comment]
@agazso Yup you're correct. I'll go over it globally. Thanks!
