### ISSUE TITLE
Color picker is a rectangle in Firefox

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#242]
In Chrome it is a circle as it is by design.

![Screenshot from 2023-08-02 23-35-41](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/48141b77-b45f-424d-ad52-af0ff3e35af3)

**Comment by sugarpusher** [comment]
@agazso are you still seeing this issue? I checked when you created the issue and confirmed it, I was going to work on it now however I can no longer reproduce.
Thanks!

**Comment by agazso** [comment]
Yes, I still have it, but it looks like a Firefox bug to me. You can treat it as low priority.
