### ISSUE TITLE
Numbers in chats list show total messages

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-playground#247]
<img width="176" alt="Screenshot 2023-08-03 at 13 13 38" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/202e5c3c-ab7e-45c0-af6d-74a93a5a6071">

In the original design they show new messages, if we don't have this feature then I would simply remove that number

**Comment by vojtechsimetka** [comment]
Doable, easy on single device, likely more involved to have it sinced cross device. From my point of view this is not high priority right now.

**Comment by sugarpusher** [comment]
Ok - I'll remove the counter for now and close this issue. We can create a new issue for it as enhancement. Thanks
