### ISSUE TITLE
Lost chats after domain change

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-playground#248]
When I reconnected my existing identity after the domain change (with chats created before the domain change) the old chats were lost

**Comment by vojtechsimetka** [comment]
When did you made these chats? Are you sure these were not done on `firebase`? Because we completely dropped that DB and we use waku with blockchain. All my chats work correctly on both domains.

**Comment by david-gauquelin** [comment]
these chats were done when we met in Balaton, so I guess yes firebase

**Comment by vojtechsimetka** [comment]
OK then I assume this is not an issue. Closing
