### ISSUE TITLE
Chat bubble text cannot be selected in Firefox

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#250]

**Comment by sugarpusher** [comment]
@agazso I thought we decided that they should be selectable. Can you confirm or deny @david-gauquelin @vojtechsimetka?

**Comment by agazso** [comment]
Exactly, and the problem is that I cannot select the text.

**Comment by sugarpusher** [comment]
That's weird, I can 🤔
Where are you testing? I can select both on desktop and my android

**Comment by agazso** [comment]
Indeed it works in Chrome. It does not work in Firefox. Updated the title.

**Comment by agazso** [comment]
Sorry, false alarm, it only does that when I view it on mobile view in the dev tools :smile:
