### ISSUE TITLE
When the last message is long name is split into two lines

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#263]
In the main chat list screen, when the last message from the chat is long then the name is split into two line. It would be better if the name was kept in one line and the message would be cut shorter instead.

![Screenshot from 2023-08-04 13-59-38](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/7166808c-e7f5-4d63-929d-1332af12ba0d)

**Comment by sugarpusher** [comment]
@agazso 
On the chat list screen the name should always be on its own line, so I'm not sure it's even on the same line as the text for you. I'll take a look at that.
But also, you shouldn't have the count badge anymore, Vojtech removed it yesterday I think. Are you up to date with main?

<img width="489" alt="Screenshot 2023-08-04 at 9 30 30 AM" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/16855117/3994e9ca-2988-4e99-823f-b2df6dd83cd8">

**Comment by agazso** [comment]
> @agazso On the chat list screen the name should always be on its own line, so I'm not sure it's even on the same line as the text for you. I'll take a look at that. But also, you shouldn't have the count badge anymore, Vojtech removed it yesterday I think. Are you up to date with main?
> <img alt="Screenshot 2023-08-04 at 9 30 30 AM" width="489" src="https://user-images.githubusercontent.com/16855117/258434228-3994e9ca-2988-4e99-823f-b2df6dd83cd8.png">

Good point, I was on the group chat branch. Please disregard this.
