### ISSUE TITLE
Group invite does not work if you are offline

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#267]
>     * [ ]  if I am offline and someone invites me to a group I don't become part of the group

_Originally posted by @vojtechsimetka in https://github.com/logos-innovation-lab/waku-objects-playground/pull/228#pullrequestreview-1563048288_

**Comment by vojtechsimetka** [comment]
This is fixed, right @agazso ?

**Comment by agazso** [comment]
Yes, there is a temporary fix for this: #272
