### ISSUE TITLE
Payggy should be disabled in group chat or support groups

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#269]
- [ ] payggy should be disabled in group if there is more than 2 users in total (the recipient is kinda selected at random in this case). Or we should allow the sender to choose from the group members who should be the recipient (I quite like this).

_Originally posted by @vojtechsimetka in https://github.com/logos-innovation-lab/waku-objects-playground/pull/228#pullrequestreview-1563048288_

**Comment by vojtechsimetka** [comment]
Resolved by #290
