### ISSUE TITLE
Group chat styling and the Join screen is missing

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#270]
Related: #228 

- [x] names and avatars of the chat participants on the message bubbles
- [x] create screen styling, invite component (also invite to group)
- [x] group settings page
- [x] join screen

**Comment by sugarpusher** [comment]
Current status @agazso 

- [ ] names and avatars of the chat participants on the message bubbles (I've added these but need to only show on the person's last bubble. Not sure how identify the person's last bubble yet, might need help)
- [ ] create screen styling, invite component (also invite to group) (I believe this is done)
- [ ] group settings page (I believe this is done)
- [ ] join screen (I'm not sure what this is. Currently the chat just appears on the invitee's chats list. Is there a mechanism implemented where they can choose to join or not?)

**Comment by agazso** [comment]
> Current status @agazso
> 
>     * [ ]  names and avatars of the chat participants on the message bubbles (I've added these but need to only show on the person's last bubble. Not sure how identify the person's last bubble yet, might need help)

The person's last message is when going through the messages, the next message is from a different person or there are no more messages.

>     * [x]  create screen styling, invite component (also invite to group) (I believe this is done)

- [ ] The group settings icon is not the correct one (should be three dots).
- The invite component is currently missing the selected members above the invite button, both in the create group and in the group settings page. I don't think it's important for now. Sketch screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/L4nyKe5
- [ ] Currently there is an invite icon next to all members of a group (except you). It should be an invite icon only for those members who are not your contacts. For your contacts it should be the three dots icon, or if we don't implement the functionality from the menu then there should be no icon.

>     * [ ]  join screen (I'm not sure what this is. Currently the chat just appears on the invitee's chats list. Is there a mechanism implemented where they can choose to join or not?)

This is what I called the join screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/YZ5e4nd

**Comment by sugarpusher** [comment]
> > ```
> > * [ ]  names and avatars of the chat participants on the message bubbles (I've added these but need to only show on the person's last bubble. Not sure how identify the person's last bubble yet, might need help)
> > ```
> 
> The person's last message is when going through the messages, the next message is from a different person or there are no more messages. (I know the logic but not sure how to implement it 😉. I gave it a try a few days ago but will look into it some more.)
> 
> > ```
> > * [x]  create screen styling, invite component (also invite to group) (I believe this is done)
> > ```
> 
> * [ ]  The group settings icon is not the correct one (should be three dots). (Yes but we currently only have one action so I left it as it's more indicative of what the action is, and it's only one click instead of 2. The gear icon could also work there but I'll ask @david-gauquelin )
> * The invite component is currently missing the selected members above the invite button, both in the create group and in the group settings page. I don't think it's important for now. Sketch screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/L4nyKe5 (Yup I did see this one but I thought it was an enhancement so I didn't work on it. If it's not, I can)
> * [ ]  Currently there is an invite icon next to all members of a group (except you). It should be an invite icon only for those members who are not your contacts. For your contacts it should be the three dots icon, or if we don't implement the functionality from the menu then there should be no icon. (Not exactly. Next to members that are your contacts, the link takes you to the existing that. It's also a slightly different icon. I didn't use the three dots for the same reason as the "edit chat", there's only one action so it's a direct link.)
> 
> > ```
> > * [ ]  join screen (I'm not sure what this is. Currently the chat just appears on the invitee's chats list. Is there a mechanism implemented where they can choose to join or not?)
> > ```
> 
> This is what I called the join screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/YZ5e4nd (thank you. Does this screen appear once invitee clicks on the group chat for the first time?)

**Comment by agazso** [comment]
> > * The invite component is currently missing the selected members above the invite button, both in the create group and in the group settings page. I don't think it's important for now. Sketch screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/L4nyKe5
> 
> Yup I did see this one but I thought it was an enhancement so I didn't work on it. If it's not, I can

As far as I am concerned it is not necessary, but a nice to have.

> > * [ ]   Currently there is an invite icon next to all members of a group (except you). It should be an invite icon only for those members who are not your contacts. For your contacts it should be the three dots icon, or if we don't implement the functionality from the menu then there should be no icon.
> 
> Not exactly. Next to members that are your contacts, the link takes you to the existing chat. It's also a slightly different icon. I didn't use the three dots for the same reason as the "edit chat", there's only one action so it's a direct link.

I see. There is very little difference between the icons though so it can be confusing, as illustrated with my case.

> > This is what I called the join screen: https://www.sketch.com/s/4019db99-51a1-4c60-82d3-65b09535181d/a/YZ5e4nd
> 
> thank you. Does this screen appear once invitee clicks on the group chat for the first time?

Yes.

There is one more issue I found:
- [ ] On the invite screen the `Create group` has the wrong icon and also the alignment of the icon is wrong.

**Comment by agazso** [comment]
Closed by #301
