### ISSUE TITLE
Payggy: button to access transaction details should be the whole grey area

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/waku-objects-playground#275]
@david-gauquelin is this true?

_@agazso wrote_ 
> I think by design the gray area on the widget is clickable, not just the icon. Otherwise the icon is too small, so the click area should be larger (for phones)

<img width="336" alt="Screenshot 2023-08-04 at 21 01 08" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/7974813/6d487fce-3f85-4230-b078-07fa7165d58a">

**Comment by david-gauquelin** [comment]
Yes the whole area is clickable

**Comment by sugarpusher** [comment]
Solved on #277
