### ISSUE TITLE
Adapter throws CSP error on Firefox

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#337]
On Chrome it works without issues.

Here is the warnings and errors on Firefox:
![Screenshot from 2023-08-31 16-43-03](https://github.com/logos-innovation-lab/waku-objects-playground/assets/230163/e172b9cd-1151-4aab-a749-8a075d8fca73)

**Comment by agazso** [comment]
It seems that the problem is with the `script-src` in the `meta` Content-Security-Policy header in the `template.html`. If that is removed then the objects load correctly in Firefox too.

Also it would be interesting to apply a CSP header for the app and maybe the child iframes would inherit those?

**Comment by filoozom** [comment]
Closed in #358.
