### ISSUE TITLE
Add image on welcome screen

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/waku-objects-playground#348]
It would be a nice welcome 
<img width="308" alt="Screenshot 2023-09-06 at 15 29 08" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/9036081/87f15845-c31e-4ee4-8328-70d86d394067">

**Comment by agazso** [comment]
There is already an issue opened for this: https://github.com/logos-innovation-lab/waku-objects-playground/issues/327

**Comment by kikipluche** [comment]
ok, i will close this one
