### ISSUE TITLE
payggy object keeps in loading state on receiver side

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/waku-objects-playground#350]
<img width="521" alt="Screenshot 2023-09-06 at 16 31 12" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/9036081/7a314b4b-336b-403a-91dc-0915626fc6fc">

**Comment by agazso** [comment]
Which version did you use to make the Payggy transactions? About a month ago there was a breaking change and Payggy objects before that no long work in the current version.

**Comment by kikipluche** [comment]
i am testing on what is currently on chat.wakuplay.im
