### ISSUE TITLE
change Payggy title description?

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/waku-objects-playground#376]
it says: Send or request payment.

Should we change this to send payment in order to match the current version, or keep the send and request to refer to the goal of payggy

**Comment by agazso** [comment]
I would change it to `Make a payment privately or in a group" to emphasize what we actually implemented.

**Comment by kikipluche** [comment]
or just "make a payment"

**Comment by david-gauquelin** [comment]
We discussed this already in the summer, now the design says "Send payments to chat members", would that work?
