### ISSUE TITLE
Ask to settle gives wrong message on receiver side

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/waku-objects-playground#377]
Ask to settle button generates the message "all settled"
<img width="912" alt="Screenshot 2023-09-12 at 11 43 27" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/9036081/0b4f30b4-a717-4d43-9f36-fa91c6ad02b5">

**Comment by kikipluche** [comment]
@vojtechsimetka this still happens on my side, why/

**Comment by vojtechsimetka** [comment]
Let's debug together. I bet  there is some other underlying issue which may also explain other things.

**Comment by kikipluche** [comment]
we figured it out, everything is working :-) thanks @vojtechsimetka
