### ISSUE TITLE
Confusing wording for new chats

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-playground#431]
- I share my invite to chat link with someone
- That person clicks on the invite link and selects "Start a new chat"
- On my side I see "X invited you to chat privately" (see attached images)

**I would replace the wording with "X wants to chat privately"**

<img width="557" alt="Screenshot 2023-09-22 at 11 11 54" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/e2b38fa2-895d-4056-b4e6-47be5b610cd7">
<img width="691" alt="Screenshot 2023-09-22 at 11 19 11" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/a09a4646-ccc7-40b6-b82c-11191514cf5e">

**Comment by agazso** [comment]
Do you also want to change the wording for group chat? This comes from the sketch file: https://www.sketch.com/s/cbdf10a1-c69e-4370-9793-7b89f54452e0/a/OeOgr9q

**Comment by david-gauquelin** [comment]
I know it's a bit confusing but in the Sketch file you shared this shows when someone invited me to a private through a group. In this case there's no landing page and a new chat appears directly to your chat list. But I think that if we change the wording as I suggested it works for every case

**Comment by agazso** [comment]
Okay, maybe I was indeed confusing, the sketch link I shared above is for the private invite, which is this issue about. And it contains exactly what is implemented. It is not a problem changing it in the code, however it would be good to update the sketch file too to avoid further misunderstandings.

The reason I asked about the group chat is because if we need to change the wording for the invites then I would prefer to do it at once together with the group chats, rather as a separate issue in the future.

**Comment by david-gauquelin** [comment]
for group chat it's a different wording (see attached image)
<img width="957" alt="Screenshot 2023-09-25 at 11 19 22" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/918bf08a-618b-4660-925b-36313ece2cfe">

for private chats there are 2 different scenarios:
1. someone access your invite link
2. someone invites you to a private chat from a group where you're both members

In the first case, when someone accessed your link and selected "start a new chat" this is the scenario I described in the issue description on top, I would display the text ""X wants to chat privately" when the chat appears on my list

In the second case, when someone asked me to chat from a group members list, we can also use the same wording ""X wants to chat privately"
