### ISSUE TITLE
Weird spacing between buttons on invite landing

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/waku-objects-playground#433]
<img width="691" alt="Screenshot 2023-09-22 at 11 19 11" src="https://github.com/logos-innovation-lab/waku-objects-playground/assets/46993354/3a725bb2-00d4-43ad-9972-81937d4d45f2">

it should be 12pt as everywhere else

**Comment by agazso** [comment]
Closed by #437
