### ISSUE TITLE
splitterFactory address is hardcoded in the BlockchainNetwork type

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#450]
> I just realized that the `splitterFactory` address is hardcoded in the `BlockchainNetwork` type. I don't think that's a good place to store it, it seems it would be better if the object code would define it, especially if the object is an external type then there is no way that it can expect the host application to know about it and expose it in the SDK.

_Originally posted by @agazso in https://github.com/logos-innovation-lab/waku-objects-playground/pull/399#discussion_r1330099175_

**Comment by vojtechsimetka** [comment]
But if we do this, then we need to expose `chainId` to the object

**Comment by agazso** [comment]
Yeah, let's do that! I would put this in the `WakuObjectState`
