### ISSUE TITLE
Scroll to see last message

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/waku-objects-playground#55]
This should happen when:
- I send a message
- I am scrolled down looking at the last message and someone sends new message

In other instances there should likely be some indicator that new message appeared. WDYT @david-gauquelin ?

**Comment by david-gauquelin** [comment]
Yes, the indicating new messages in-chat is on my to-do list. I would group this with indicating new messages in the chats list as well

**Comment by david-gauquelin** [comment]
by the way just to be clear, the latest messages should be displayed at the bottom

**Comment by vojtechsimetka** [comment]
Stumbled across this tutorial which could be quite nice inspiration :) https://svelte.dev/tutorial/update
