### ISSUE TITLE
Connect with wallet

### ISSUE THREAD

**Issue by agazso** [logos-innovation-lab/waku-objects-playground#8]
In order to login to the app and have an identity a wallet needs to be connected.

https://www.sketch.com/s/aa87e1e9-2fa2-46fb-b2c7-5414cdf07cb3/a/RyMy01W

**Comment by agazso** [comment]
Based on previous discussions it seems that there are at least two distinct use-cases which needs to be decided on:
- login (connect)
- signing

For the login there are at least two distinct simple ways how they can be implemented:
1. connect with external wallet (as in Kurate)
2. generating the key in memory and store it in localStorage (as in Boardwalk)

For signing there is also two distinct ways how they can be implemented:
1. sign with the external wallet
2. sign with the in-memory key

Please note that it is possible to mix these approaches by using the external wallet only to connect and derive a key (e.g. from a signature of a well known message) that can be used to store in-memory for signing later.

**Comment by agazso** [comment]
For the minimal version the consensus is to generate the key in memory and store it in localStorage and use that key for signing. Later this can be changed to use an injected wallet.

**Comment by vojtechsimetka** [comment]
Implemented in #65
